# Generated by Django 4.0.5 on 2022-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileuser', '0003_mobileproducts_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproducts',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
