# Generated by Django 4.0.5 on 2022-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileuser', '0004_mobileproducts_pro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProductss',
            fields=[
                ('pro_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=80)),
                ('pro_ram', models.CharField(max_length=80)),
                ('pro_dis', models.CharField(max_length=90)),
                ('pro_camera', models.CharField(max_length=80)),
                ('pro_battery', models.CharField(max_length=80)),
                ('pro_price', models.PositiveIntegerField()),
                ('pro_offprice', models.PositiveIntegerField(null=True)),
                ('pro_processor', models.CharField(max_length=150)),
                ('pro_warrenty', models.CharField(max_length=150)),
                ('pro_specification', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='MobileProducts',
        ),
    ]
