# Generated by Django 4.0.5 on 2022-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileuser', '0005_mobileproductss_delete_mobileproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproductss',
            name='pro_img',
            field=models.ImageField(null=True, upload_to='mobileimages'),
        ),
    ]
